#!/bin/bash

#  Count the total number of N's, X's, and BP per fasta/q sequence
#  (includes a header line as well)
#  
#  file: fastx_stats

input="${1:-/dev/stdin}"

bioawk -cfastx 'BEGIN{ 
	totalbp = 0; totalN = 0; totalX = 0;
	print "seqname", "sumbp", "sumn", "fracn", "sumx", "fracx", "meanqual"
} 
{ 
	TOTAL=length($seq);
	SUMN=0; SUMX=0; 
	SUMN+=(gsub(/n|N/,"", $seq));
	SUMX+=(gsub(/x|X/,"", $seq));
	totalN+=SUMN;
	totalX+=SUMX;
	totalbp+=TOTAL
	print $name, TOTAL, SUMN, (SUMN / TOTAL), SUMX, (SUMX / TOTAL), meanqual($qual)
} END { 
	print "_ALL_", totalbp, totalN, (totalN / totalbp), totalX, (totalX / totalbp) > "/dev/stderr"
}' $input 

