#!/bin/bash

# Filter fastq reads by length

# ARGUMENTS:
# -l INT 	The minimum length of sequences to output (default: 0)
# -n INT	Stop after processing this many reads.  When a negative value is given, all reads are processed (default: -1)


# parse arguments
MINLEN=0
NREADS=-1
while getopts "l:n:" option
do
 case "${option}" in
 l) MINLEN=${OPTARG}
shift $((OPTIND-1))
;;
 n) NREADS=${OPTARG}
shift $((OPTIND-1))
;;	
 esac
done

# echo "Argument MINLEN: $MINLEN"
# echo "Argument NREADS: $NREADS"
# echo "Argument OPTIND: ${OPTIND}"
# echo "Argument else:: ${@}"


bioawk -c fastx -v minlen=${MINLEN} -v maxreads=${NREADS} '{
if( maxreads > 0 && NR > maxreads ){ 
	exit 0;
}
if(length($seq) >= minlen){
	if(length($qual) != 0){
		print "@"$name"\n"$seq"\n+"$comment"\n"$qual 
	} else {
		print ">"$name"\n"$seq
	}
}

}' $@





