package:
  name: gtools
  version: "0.1.0"

source:
  git_url: https://github.com/ConradStack/gtools
  git_rev: v0.1.0
  
requirements:
  build:
    - python
  run:
    - python
    - bioawk
    - samtools >=1.3.1

about:
  home: https://github.com/ConradStack/gtools/
  license: BSD