#!/bin/bash

# 	Filter a SAM-formatted file for paired reads that map on to different references
# 

input="${1:-/dev/stdin}"

# Conditions are:
# 1. read is not unmapped and mate is not unmapped (int code 12)
# 2. read's ref name and mate's ref name is not the same
# 3. mate's ref name is not '=', which indicates that the ref for read and mate is equal
#  	(note:  2 & 3 are likely redundant -- check the SAM spec to see if '=' is required when references for read and mate are identical. )
bioawk -c sam '!and($flag,12) && $rnext != $rname && $rnext != "="' $input

