#!/bin/bash

#	Return the overall maximum quality score as ASCII integer from a set of fastQ reads.  
#  	 - (default) Only work on first 1000 entries
#	n.b. -> bioawk already subtracts 33 from the quality characters.  
#			Another 31 would need to be subtracted for Phred+64 (e.g., illumina [1.3 to 1.8) )

input="${1:-/dev/stdin}"
	
bioawk -c fastx 'BEGIN{x=0;MAX=-150} 
{ 
	if(NR <= 10000){
		x=maxqual($qual); 
		MAX = (MAX > x ? MAX : x);		
	} else {
		exit;
	}
} 
END{ print MAX+33 }' ${input}
