#!/bin/bash

# A script that generates synthetic read pairs from opposing ends of each input sequence (e.g., each contig or scaffold of a genome assembly)

# ARGUMENTS:
# -l INT 	The length of each read pair, L (default: 1000).  Read pairs that overlap are not generated, so the effective minimum size of input sequences is 2*L

# NOTES:
# - Output reads pairs are interleaved in illumina-style Forward-Reverse ('innie') orientation

# parse arguments
MINLEN=1000
while getopts "l:" option
do
 case "${option}" in
 l) MINLEN=${OPTARG}
#shift $((OPTIND-1))
;;
 esac
done

shift $((OPTIND-1))
# echo "Argument MINLEN: $MINLEN"  # 
# echo $@

bioawk -c fastx -v minlen=${MINLEN} '{
slen=length($seq)

if(slen >= (minlen*2)){
	seqhead=substr($seq, 0, minlen)
	seqtail=revcomp(substr($seq, (slen-minlen+1), slen))

	if(length($qual) != 0){
		qualhead=substr($qual, 0, minlen)
		qualtail=revcomp(substr($qual, (slen-minlen+1), slen))

		print "@"$name"/1\n"seqhead"\n+\n"qualhead
		print "@"$name"/2\n"seqtail"\n+\n"qualtail
	} else {
		print ">"$name"/1\n"seqhead
		print ">"$name"/2\n"seqtail
	}
}

}' $@



