#!/bin/bash

#  Calculates size statistics of the sequence in a fastx file.
#  
#  file: fastx_stats

input="${1:-/dev/stdin}"

output=/dev/null
if [[ -f $input ]]; then
    _tmp2=${input}
    if [[ ${input} == *.gz ]]; then
        _tmp2=${input%.gz}
    fi
    if [[ ! -s ${_tmp2}.stats ]]; then
        output=${_tmp2}.stats
    else
        printf "Warning: default output file (%s) already exists.  Not overwriting\n" ${output} >> /dev/stderr
    fi
fi

fastx_lengths ${input} | size_stats - | datamash transpose | tee ${output}

