#!/bin/bash

# Count the number of sequences in a set of fasta/q sequences

input="${1:-/dev/stdin}"

# I'm not sure, but bioawk might loose precision on large data sets (TODO: check this)
bioawk -c fastx '{ print ">"$name"\n"$seq }' $input

