#!/bin/bash

# Sum all of the intervals in a bed file (including intervals that could overlap with each other). 
# 
# nb -> uses bioawk

input="${1:-/dev/stdin}"

bioawk -cbed '{SUM += ($end-$start) } END {print SUM}' $input
